# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_app.Response')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_app.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='responsecreation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_app.User'),
        ),
        migrations.AddField(
            model_name='responsecreation',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_app.Response'),
        ),
        migrations.AddField(
            model_name='responsecreation',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_app.Thread'),
        ),
    ]
